modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

issueTrackerURL="https://github.com/Kishku7/mod_support/issues"
[[mods]]
modId="bankvault"
version="${version}"
displayName="Bank Vault"
authors="Kishku7"
description='''A single multiblock vault with a creative-style categorized GUI. Form a 3x3 of Bank Vault blocks and store everything.'''

[[dependencies.bankvault]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.bankvault]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
