modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"

[[mods]]
    modId = "bankvault"
    version = "${mod_version}"
    displayName = "Bank Vault"
    authors = "Kishku7"
    description = '''A single multiblock vault with a creative-style categorized GUI. Form a 3x3 of Bank Vault blocks and store everything.'''

[[dependencies.bankvault]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoforgeRange}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.bankvault]]
    modId = "minecraft"
    type = "required"
    versionRange = "${mcRange}"
    ordering = "NONE"
    side = "BOTH"
